logging:
  version: 1
  disable_existing_loggers: false
  formatters:
    simple:
      format: "%(asctime)s - %(name)s:%(lineno)d - [%(levelname)s] - %(message)s"
  handlers:
    console:
      class: logging.StreamHandler
      level: DEBUG
      formatter: simple
    file:
      class: logging.handlers.TimedRotatingFileHandler
      when: midnight
      backupCount: 90
      level: INFO
      formatter: simple
      filename: main.log
  loggers:
    pika:
      level: WARNING
      handlers:
        - console
        - file
      propagate: yes
  root:
    level: INFO
    handlers:
      - console
      - file
path:
  logs: logs
db:
  name: db/pyranseqbot
  connect_retry:
    count: 2
    delay: 10